### PR TITLE
8.2XS82ECU1050

### PR DESCRIPTION
**Pull request by gduperrey**

### CODE REVIEW

**Comment by stormi** [comment]
The branch conflicts

**Comment by gduperrey** [comment]
How can i see that?
I used everything in the doc, and I don't see if there is a problem.

**Comment by stormi** [comment]
My bad: the UI had set the merge button to "Rebase and merge" by default (because I likely used it in the past), and in this context, this displays a message about conflicts.

**Review by stormi — APPROVED** [review]

**Review by benjamreis — APPROVED** [review]

**Comment by gduperrey** [comment]
Koji build (v8.2-incoming): https://koji.xcp-ng.org/taskinfo?taskID=39535

**Pull request merged**
